"""category description and nullable course.category_id

Revision ID: c26359c2bfbd
Revises: 1f44764d7241
Create Date: 2025-08-22 21:10:49.872975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26359c2bfbd'
down_revision: Union[str, None] = '1f44764d7241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint(op.f('courses_category_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_category_id_fkey'), 'courses', 'categories', ['category_id'], ['id'])
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
